### PR TITLE
Allow override of parachain pallet ID and `authorize_upgrade` call ID

### LINKED ISSUE #11: Possibility to override parachain pallet ID
Hi there, I'd like to ask if there's a way to override the parachain pallet ID and authorize_upgrade index in this GHA.

I noticed there's `PARACHAIN_PALLET_ID` and `AUTHORIZE_UPGRADE_PREFIX` for subwasm and was wondering if there's a similar thing for srtool-actions. Thanks in advance!

### PR DESCRIPTION
**Pull request by Kailai-Wang**
resolves #11 

This PR adds two extra envs to allow override of parachain pallet ID and authorize_upgrade call ID

### CODE REVIEW

**Review by chevdor — CHANGES_REQUESTED** [review]
This project does not use the `readme.md` directly. The source is actually `README_src.adoc` and the md is generated. You do not need to bother about the generation itself though but could you please move your doc to the `.adoc` file ?

The syntax is almost identlical to what you have besides the url which should be `http://example.com[some text]` instead of `[some  text](http://example.com)`

**Comment by Kailai-Wang** [comment]
Thanks @chevdor 
I reverted README.md and moved the document to `examples/05_build_opts.yml`

**Comment by chevdor** [comment]
We cannot do that: the `examples/05_build_opts.yml` should be a valid yaml file.

Ideally, what we should do is create a new example, include it to the adoc and add your comments in the adoc file.
I would then merge it and regenerate the readme.

**Comment by Kailai-Wang** [comment]
sorry I didn't know that.

I tried to restructure the docs a bit according to your suggestions, please also feel free to edit directly if needed :)

I was not sure if I should include the `parachain-overrides.adoc` in the index.adoc or README_src.adoc, but I chose the latter eventually..

**Comment by chevdor** [comment]
Thank you very much for your efforts @Kailai-Wang. I can take it from here.
Note that the doc currently is erroneous as it suggests `v0.4.0` contains your overrides.
I will fix that.

**Comment by Kailai-Wang** [comment]
Thanks. I'm sure I'll do it better next time 🚀

**Pull request merged**
